"""Object configurations for the Hunger game: plants, gear stations, walls."""

from __future__ import annotations

from mettagrid.config.filter import actorHasAnyOf
from mettagrid.config.filter.filter import isNot
from mettagrid.config.handler_config import Handler, actorHas, targetHas, updateActor, withdraw
from mettagrid.config.mettagrid_config import GridObjectConfig, InventoryConfig, WallConfig
from mettagrid.config.mutation.tag_mutation import removeTag

INITIAL_PLANT_FOOD = 1
MAX_PLANT_FOOD = 100


def plant_config() -> GridObjectConfig:
    """A plant that scouts can harvest food from. Regenerated by seasonal events."""
    return GridObjectConfig(
        name="plant",
        render_name="junction",
        render_symbol="\U0001f33f",
        tags=["team:cogs_green"],
        inventory=InventoryConfig(initial={"food": INITIAL_PLANT_FOOD}, default_limit=MAX_PLANT_FOOD),
        on_use_handlers={
            "harvest_last": Handler(
                filters=[actorHas({"scout": 1}), isNot(targetHas({"food": 2}))],
                mutations=[withdraw({"food": 100}), removeTag("team:cogs_green")],
            ),
            "harvest": Handler(
                filters=[actorHas({"scout": 1})],
                mutations=[withdraw({"food": 100})],
            ),
        },
    )


def predator_station_config() -> GridObjectConfig:
    """Gear station that gives scrambler role. Once picked, cannot be changed."""
    return GridObjectConfig(
        name="predator_station",
        render_name="scrambler",
        render_symbol="\U0001f534",
        on_use_handlers={
            "has_gear": Handler(
                filters=[actorHasAnyOf(["scrambler", "scout"])],
                mutations=[],
            ),
            "get_gear": Handler(
                filters=[],
                mutations=[updateActor({"scrambler": 1})],
            ),
        },
    )


def prey_station_config() -> GridObjectConfig:
    """Gear station that gives scout role. Once picked, cannot be changed."""
    return GridObjectConfig(
        name="prey_station",
        render_name="scout",
        render_symbol="\U0001f535",
        on_use_handlers={
            "has_gear": Handler(
                filters=[actorHasAnyOf(["scrambler", "scout"])],
                mutations=[],
            ),
            "get_gear": Handler(
                filters=[],
                mutations=[updateActor({"scout": 1})],
            ),
        },
    )


def wall_config() -> WallConfig:
    return WallConfig(name="wall", render_symbol="\u2b1b")
