apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "cronjob.selectorLabels" . | nindent 12 }}
            {{- if .Values.datadog.enabled }}
            tags.datadoghq.com/env: {{ required "datadog.env is required" .Values.datadog.env | quote }}
            # each cronjob gets its own release name
            tags.datadoghq.com/service: {{ .Release.Name | quote }}
            tags.datadoghq.com/version: {{ .Values.image.tag | quote }}
            admission.datadoghq.com/enabled: true
            {{- end }}
        spec:

          serviceAccountName: {{ include "cronjob.serviceAccountName" . }}
          restartPolicy: {{ .Values.restartPolicy }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ if .Values.image.registry }}{{ .Values.image.registry }}/{{ end }}{{ .Values.image.name }}:{{ required "tag is required" .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            # Command comes from Dockerfile CMD
            # Secrets are fetched from AWS Secrets Manager at runtime via the serviceAccount IAM role
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
