ingress-nginx:
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    config:
      # necessary for observatory, we strip headers in observatory-api ingress
      allow-snippet-annotations: "true"
      http-snippet: |
        map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
        }
