apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.cert_manager_issuer | required "cert_manager_issuer is required" }}

spec:
  ingressClassName: nginx
  {{- $primaryHost := .Values.host | required "host is required" }}
  {{- $hosts := concat (list $primaryHost) (.Values.extraHosts | default (list)) }}
  rules:
  {{- range $host := $hosts }}
  - host: "{{ $host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}
            port:
              number: 80
  {{- end }}
  tls:
  - hosts:
    {{- range $host := $hosts }}
    - {{ $host }}
    {{- end }}
    secretName: {{ .Release.Name }}-tls
