"""add service accounts table

Revision ID: a47a7013d7d0
Revises: c90c87b3b5d6
Create Date: 2026-02-20 11:30:41.545908

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a47a7013d7d0"
down_revision: Union[str, Sequence[str], None] = "c90c87b3b5d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_accounts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_preview", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_prefix", sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'ssa_'"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "user_id", name="unique_user_sa_name"),
    )
    op.create_index(op.f("ix_service_accounts_token_hash"), "service_accounts", ["token_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_accounts_token_hash"), table_name="service_accounts")
    op.drop_table("service_accounts")
    # ### end Alembic commands ###
