# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-03-05T19:41:20+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Optional, Union
from uuid import UUID

from cogames.cli._model_base import CLIModel
from pydantic import Field


class AgentResult(CLIModel):
    agent_id: Annotated[int, Field(title="Agent Id")]
    """
    Index of the agent within the episode
    """
    reward: Annotated[float, Field(title="Reward")]
    """
    Total reward earned by this agent
    """
    metrics: Annotated[
        dict[str, float],
        Field(
            examples=[
                {
                    "action.move.failed": 51.0,
                    "action.move.success": 623.0,
                    "action.noop.success": 326.0,
                    "energy.amount": 8.0,
                    "energy.gained": 1954.0,
                    "energy.lost": 1946.0,
                    "hp.amount": 67.0,
                    "hp.gained": 1075.0,
                    "hp.lost": 1008.0,
                    "junction.aligned_by_agent": 2.0,
                    "status.max_steps_without_motion": 17.0,
                }
            ],
            title="Metrics",
        ),
    ]
    """
    Per-agent game metrics accumulated over the episode. Keys use dotted names: action stats (action.move.success, action.move.failed, action.noop.success, action.change_vibe.success, action.failed), resource stats with .amount/.gained/.lost suffixes (energy, heart, hp, influence), role stats with .amount/.gained/.lost suffixes (miner, aligner, scout, scrambler), junction.aligned_by_agent, and status.max_steps_without_motion.
    """


class BulkEpisodeUploadResponse(CLIModel):
    episodes_created: Annotated[int, Field(title="Episodes Created")]
    duckdb_s3_uri: Annotated[str, Field(title="Duckdb S3 Uri")]


class CompleteBulkUploadRequest(CLIModel):
    upload_id: Annotated[UUID, Field(title="Upload Id")]


class CompletePolicySubmitRequest(CLIModel):
    upload_id: Annotated[UUID, Field(title="Upload Id")]
    name: Annotated[str, Field(title="Name")]
    season: Annotated[Optional[str], Field(title="Season")] = None


class EpisodeQueryRequest(CLIModel):
    primary_policy_version_ids: Annotated[Optional[list[UUID]], Field(title="Primary Policy Version Ids")] = None
    episode_ids: Annotated[Optional[list[UUID]], Field(title="Episode Ids")] = None
    tag_filters: Annotated[Optional[dict[str, Optional[list[str]]]], Field(title="Tag Filters")] = None
    limit: Annotated[Optional[int], Field(title="Limit")] = 200
    offset: Annotated[Optional[int], Field(title="Offset")] = 0


class EpisodeWithTags(CLIModel):
    id: Annotated[UUID, Field(title="Id")]
    replay_url: Annotated[Optional[str], Field(title="Replay Url")] = None
    thumbnail_url: Annotated[Optional[str], Field(title="Thumbnail Url")] = None
    attributes: Annotated[Optional[dict[str, Any]], Field(title="Attributes")] = None
    eval_task_id: Annotated[Optional[UUID], Field(title="Eval Task Id")] = None
    created_at: Annotated[Any, Field(title="Created At")]
    tags: Annotated[Optional[dict[str, str]], Field(title="Tags")] = None
    avg_rewards: Annotated[Optional[dict[str, float]], Field(title="Avg Rewards")] = None
    job_id: Annotated[Optional[UUID], Field(title="Job Id")] = None


class MembershipHistoryEntry(CLIModel):
    season_name: Annotated[str, Field(title="Season Name")]
    """
    Name of the season
    """
    season_version: Annotated[Optional[int], Field(title="Season Version")] = None
    """
    Version of the season
    """
    pool_name: Annotated[str, Field(title="Pool Name")]
    """
    Name of the pool
    """
    action: Annotated[str, Field(title="Action")]
    """
    Membership action (e.g. added, removed, retired)
    """
    notes: Annotated[Optional[str], Field(title="Notes")] = None
    """
    Optional notes about the membership change
    """
    created_at: Annotated[str, Field(title="Created At")]
    """
    ISO 8601 timestamp of the membership change
    """


class PolicyCreate(CLIModel):
    name: Annotated[str, Field(title="Name")]
    attributes: Annotated[Optional[dict[str, Any]], Field(title="Attributes")] = None
    is_system_policy: Annotated[Optional[bool], Field(title="Is System Policy")] = False


class PolicyVersionCreate(CLIModel):
    policy_spec: Annotated[Optional[dict[str, Any]], Field(title="Policy Spec")] = None
    git_hash: Annotated[Optional[str], Field(title="Git Hash")] = None
    attributes: Annotated[Optional[dict[str, Any]], Field(title="Attributes")] = None
    s3_path: Annotated[Optional[str], Field(title="S3 Path")] = None


class PolicyVersionResponse(CLIModel):
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    version: Annotated[int, Field(title="Version")]
    pools: Annotated[Optional[list[str]], Field(title="Pools")] = None
    submit_error: Annotated[Optional[str], Field(title="Submit Error")] = None


class PolicyVersionSummary(CLIModel):
    id: Annotated[UUID, Field(title="Id")]
    """
    Unique identifier of the policy version
    """
    name: Annotated[Optional[str], Field(title="Name")] = None
    """
    Human-readable policy name
    """
    version: Annotated[Optional[int], Field(title="Version")] = None
    """
    Sequential version number within the policy
    """


class PoolInfo(CLIModel):
    id: Annotated[Optional[UUID], Field(title="Id")] = None
    """
    Database identifier of the pool
    """
    name: Annotated[str, Field(title="Name")]
    """
    Name of the pool
    """
    description: Annotated[str, Field(title="Description")]
    """
    Human-readable description of the pool
    """
    config_id: Annotated[Optional[UUID], Field(title="Config Id")] = None
    """
    Identifier of the pool's environment configuration
    """


class PoolMembership(CLIModel):
    pool_name: Annotated[str, Field(title="Pool Name")]
    """
    Name of the pool
    """
    active: Annotated[bool, Field(title="Active")]
    """
    Whether the policy is currently active in this pool
    """
    completed: Annotated[int, Field(title="Completed")]
    """
    Number of completed matches
    """
    failed: Annotated[int, Field(title="Failed")]
    """
    Number of failed matches
    """
    pending: Annotated[int, Field(title="Pending")]
    """
    Number of pending matches
    """


class PresignedUploadUrlResponse(CLIModel):
    upload_url: Annotated[str, Field(title="Upload Url")]
    s3_key: Annotated[str, Field(title="S3 Key")]
    upload_id: Annotated[UUID, Field(title="Upload Id")]


class Kind(Enum):
    policy_eval = "policy_eval"
    sample_teams = "sample_teams"
    team_eval = "team_eval"
    score_policies = "score_policies"


class Status(Enum):
    complete = "complete"
    active = "active"
    pending = "pending"


class ProgressStage(CLIModel):
    index: Annotated[int, Field(title="Index")]
    """
    1-indexed position of this stage in TeamTournamentConfig.stages
    """
    name: Annotated[str, Field(title="Name")]
    """
    Human-readable stage title for UI display
    """
    kind: Annotated[Kind, Field(title="Kind")]
    """
    Configured stage kind: policy_eval, sample_teams, team_eval, or score_policies
    """
    description: Annotated[str, Field(title="Description")]
    """
    Resolved stage description derived from configured stage parameters
    """
    input_pool: Annotated[str, Field(title="Input Pool")]
    """
    Name of the pool this stage reads from
    """
    output_pool: Annotated[str, Field(title="Output Pool")]
    """
    Name of the pool this stage materializes/writes when complete
    """
    status: Annotated[Status, Field(title="Status")]
    """
    Progress marker: complete = stage completion condition satisfied (output materialized/populated), active = first incomplete stage, pending = later stages
    """


class ScorePoliciesLeaderboardEntry(CLIModel):
    rank: Annotated[int, Field(title="Rank")]
    """
    1-indexed position on the score-policies leaderboard
    """
    policy: PolicyVersionSummary
    """
    Identity of the ranked policy version
    """
    placement_score: Annotated[float, Field(title="Placement Score")]
    """
    Sum of a policy's best team placements (top_k). Missing appearances are penalized as (total ranked teams + 1).
    """
    team_appearances: Annotated[int, Field(title="Team Appearances")]
    """
    Number of ranked teams containing this policy
    """
    team_ranks: Annotated[list[int], Field(title="Team Ranks")]
    """
    Sorted 1-indexed team ranks where this policy appears in the source team pool used for score-policies placement scoring
    """


class TournamentType(Enum):
    freeplay = "freeplay"
    team = "team"


class Status1(Enum):
    not_started = "not_started"
    in_progress = "in_progress"
    complete = "complete"


class SeasonDetail(CLIModel):
    id: Annotated[UUID, Field(title="Id")]
    """
    Unique season identifier
    """
    name: Annotated[str, Field(title="Name")]
    """
    Short name of the season
    """
    display_name: Annotated[str, Field(title="Display Name")]
    """
    Human-readable season title for UI display
    """
    version: Annotated[int, Field(title="Version")]
    """
    Season version number
    """
    canonical: Annotated[bool, Field(title="Canonical")]
    """
    Whether this is the canonical (active) version
    """
    summary: Annotated[str, Field(title="Summary")]
    """
    Human-readable description of the season
    """
    game_description: Annotated[Optional[str], Field(title="Game Description")] = ""
    """
    Markdown description of the game and its rules
    """
    entry_pool: Annotated[Optional[str], Field(title="Entry Pool")] = None
    """
    Name of the pool where new policies are submitted
    """
    leaderboard_pool: Annotated[Optional[str], Field(title="Leaderboard Pool")] = None
    """
    Name of the pool used for the leaderboard
    """
    is_default: Annotated[bool, Field(title="Is Default")]
    """
    Whether this is the default season
    """
    compat_version: Annotated[Optional[str], Field(title="Compat Version")] = None
    """
    Compatibility version string (e.g. '0.4')
    """
    created_at: Annotated[str, Field(title="Created At")]
    """
    ISO 8601 timestamp when this season version was created
    """
    public: Annotated[bool, Field(title="Public")]
    """
    Whether this season is visible to non-Softmax users
    """
    tournament_type: Annotated[TournamentType, Field(title="Tournament Type")]
    """
    Tournament format
    """
    pools: Annotated[list[PoolInfo], Field(title="Pools")]
    """
    Pools in this season
    """
    status: Annotated[Status1, Field(title="Status")]
    """
    High-level tournament status inferred from season/progress state
    """
    started_at: Annotated[Optional[str], Field(title="Started At")] = None
    """
    ISO 8601 timestamp when the season was started
    """
    entrant_count: Annotated[int, Field(title="Entrant Count")]
    """
    Unique policy versions that have entered the season
    """
    active_entrant_count: Annotated[int, Field(title="Active Entrant Count")]
    """
    Unique non-retired policy versions still active in the season
    """
    match_count: Annotated[int, Field(title="Match Count")]
    """
    Total matches created across all pools in this season
    """
    stage_count: Annotated[int, Field(title="Stage Count")]
    """
    Number of configured stages
    """


class SeasonSummary(CLIModel):
    id: Annotated[UUID, Field(title="Id")]
    """
    Unique season identifier
    """
    name: Annotated[str, Field(title="Name")]
    """
    Short name of the season
    """
    display_name: Annotated[str, Field(title="Display Name")]
    """
    Human-readable season title for UI display
    """
    version: Annotated[int, Field(title="Version")]
    """
    Season version number
    """
    canonical: Annotated[bool, Field(title="Canonical")]
    """
    Whether this is the canonical (active) version
    """
    summary: Annotated[str, Field(title="Summary")]
    """
    Human-readable description of the season
    """
    game_description: Annotated[Optional[str], Field(title="Game Description")] = ""
    """
    Markdown description of the game and its rules
    """
    entry_pool: Annotated[Optional[str], Field(title="Entry Pool")] = None
    """
    Name of the pool where new policies are submitted
    """
    leaderboard_pool: Annotated[Optional[str], Field(title="Leaderboard Pool")] = None
    """
    Name of the pool used for the leaderboard
    """
    is_default: Annotated[bool, Field(title="Is Default")]
    """
    Whether this is the default season
    """
    compat_version: Annotated[Optional[str], Field(title="Compat Version")] = None
    """
    Compatibility version string (e.g. '0.4')
    """
    created_at: Annotated[str, Field(title="Created At")]
    """
    ISO 8601 timestamp when this season version was created
    """
    public: Annotated[bool, Field(title="Public")]
    """
    Whether this season is visible to non-Softmax users
    """
    tournament_type: Annotated[TournamentType, Field(title="Tournament Type")]
    """
    Tournament format
    """
    pools: Annotated[list[PoolInfo], Field(title="Pools")]
    """
    Pools in this season
    """


class SeasonVersionInfo(CLIModel):
    version: Annotated[int, Field(title="Version")]
    """
    Season version number
    """
    canonical: Annotated[bool, Field(title="Canonical")]
    """
    Whether this is the canonical (active) version
    """
    disabled_at: Annotated[Optional[str], Field(title="Disabled At")] = None
    """
    ISO 8601 timestamp when this version was disabled
    """
    created_at: Annotated[str, Field(title="Created At")]
    """
    ISO 8601 timestamp when this version was created
    """
    compat_version: Annotated[Optional[str], Field(title="Compat Version")] = None
    """
    Compatibility version string (e.g. '0.4')
    """


class StageStats(CLIModel):
    name: Annotated[str, Field(title="Name")]
    """
    Pool identifier for this stage row (Pool.name), such as 'stage-1', 'sample-1', or 'team-round-2'
    """
    policy_count: Annotated[Optional[int], Field(title="Policy Count")] = 0
    """
    Number of policy memberships (PoolPlayer rows) counted for this pool under the endpoint rules
    """
    match_count: Annotated[Optional[int], Field(title="Match Count")] = 0
    """
    Total number of matches in this pool across all statuses
    """
    completion_pct: Annotated[Optional[float], Field(title="Completion Pct")] = 0.0
    """
    Completed-match percentage for this pool: completed / total_matches * 100
    """
    team_count: Annotated[Optional[int], Field(title="Team Count")] = None
    """
    Number of team records in this pool (null when this pool has no teams)
    """
    eliminated_count: Annotated[Optional[int], Field(title="Eliminated Count")] = None
    """
    Number of teams in this pool with eliminated=true (null when team_count is null)
    """


class SubmitRequest(CLIModel):
    policy_version_id: Annotated[UUID, Field(title="Policy Version Id")]
    """
    ID of the policy version to submit
    """


class SubmitResponse(CLIModel):
    pools: Annotated[list[str], Field(title="Pools")]
    """
    Names of pools the policy was added to
    """


class TeamCogSummary(CLIModel):
    position: Annotated[int, Field(title="Position")]
    """
    0-indexed slot position of this cog inside the team
    """
    policy: PolicyVersionSummary
    """
    Policy version backing this team slot
    """


class TeamSummary(CLIModel):
    id: Annotated[UUID, Field(title="Id")]
    """
    Unique team identifier
    """
    pool_name: Annotated[str, Field(title="Pool Name")]
    """
    Name of the pool (stage bucket) where this team record exists
    """
    eliminated: Annotated[bool, Field(title="Eliminated")]
    """
    Whether this team was culled in its team-eval round
    """
    score: Annotated[Optional[float], Field(title="Score")] = None
    """
    Team score computed for elimination ranking in its current round, if scored
    """
    matches: Annotated[Optional[int], Field(title="Matches")] = 0
    """
    Number of completed match records linked to this team_id
    """
    cogs: Annotated[list[TeamCogSummary], Field(title="Cogs")]
    """
    Ordered team composition; each cog is one slot containing a policy version
    """
    created_at: Annotated[str, Field(title="Created At")]
    """
    ISO 8601 timestamp when this team row was created
    """


class Phase(Enum):
    policy_eval = "policy_eval"
    sample_teams = "sample_teams"
    team_eval = "team_eval"
    score_policies = "score_policies"


class TeamTournamentProgress(CLIModel):
    phase: Annotated[Union[Phase, str], Field(title="Phase")]
    """
    Current workflow phase: first incomplete stage kind, or 'complete' when all stages are complete
    """
    phase_detail: Annotated[Optional[dict[str, Union[str, int]]], Field(title="Phase Detail")] = None
    """
    Phase metadata. When phase != 'complete', includes {'pool': input_pool_name, 'stage_index': 1-indexed stage index}; otherwise {}
    """
    stages: Annotated[list[StageStats], Field(title="Stages")]
    """
    Stage statistics for each configured stage input pool, plus the score pool
    """
    stage_flow: Annotated[Optional[list[ProgressStage]], Field(title="Stage Flow")] = None
    """
    Ordered stage plan derived from TeamTournamentConfig.stages with current completion state
    """
    started: Annotated[Optional[bool], Field(title="Started")] = False
    """
    Whether Season.started_at is set (entry policy-eval waits until this is true)
    """


class UUIDResponse(CLIModel):
    id: Annotated[UUID, Field(title="Id")]


class UserRow(CLIModel):
    id: Annotated[str, Field(title="Id")]
    name: Annotated[Optional[str], Field(title="Name")] = None
    email: Annotated[Optional[str], Field(title="Email")] = None
    is_softmax_team_member: Annotated[Optional[bool], Field(title="Is Softmax Team Member")] = None
    discord_id: Annotated[Optional[str], Field(title="Discord Id")] = None


class ValidationError(CLIModel):
    loc: Annotated[list[Union[str, int]], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]
    input: Annotated[Optional[Any], Field(title="Input")] = None
    ctx: Annotated[Optional[dict[str, Any]], Field(title="Context")] = None


class EpisodeQueryResponse(CLIModel):
    episodes: Annotated[list[EpisodeWithTags], Field(title="Episodes")]


class HTTPValidationError(CLIModel):
    detail: Annotated[Optional[list[ValidationError]], Field(title="Detail")] = None


class LeaderboardEntry(CLIModel):
    rank: Annotated[int, Field(title="Rank")]
    """
    1-indexed position on the leaderboard
    """
    policy: PolicyVersionSummary
    """
    Identity of the ranked policy version
    """
    score: Annotated[float, Field(title="Score")]
    """
    Elo or rating score
    """
    score_stddev: Annotated[Optional[float], Field(title="Score Stddev")] = None
    """
    Standard deviation of per-match policy scores under the leaderboard weighting.
    """
    score_percentiles: Annotated[Optional[dict[str, float]], Field(title="Score Percentiles")] = None
    """
    Weighted percentiles of per-match policy scores, keyed by percentile (e.g. 30, 60, 90).
    """
    matches: Annotated[int, Field(title="Matches")]
    """
    Number of matches played
    """


class MatchPlayerInfo(CLIModel):
    policy: PolicyVersionSummary
    """
    Identity of the participating policy version
    """
    num_agents: Annotated[int, Field(title="Num Agents")]
    """
    Number of agents controlled by this policy in the match
    """
    score: Annotated[Optional[float], Field(title="Score")] = None
    """
    Score awarded to this player, if the match completed
    """


class PolicyResult(CLIModel):
    position: Annotated[int, Field(title="Position")]
    """
    Policy position index in the match assignment
    """
    policy: PolicyVersionSummary
    """
    Identity of the policy version
    """
    num_agents: Annotated[int, Field(title="Num Agents")]
    """
    Number of agents controlled by this policy
    """
    avg_reward: Annotated[float, Field(title="Avg Reward")]
    """
    Mean reward across all agents for this policy
    """
    avg_metrics: Annotated[dict[str, float], Field(title="Avg Metrics")]
    """
    Mean of each metric across all agents for this policy. Same keys as AgentResult.metrics — see that field for the full key reference.
    """
    agents: Annotated[list[AgentResult], Field(title="Agents")]
    """
    Per-agent breakdown of rewards and metrics
    """


class PolicyRow(CLIModel):
    user_id: Annotated[str, Field(title="User Id")]
    user: Optional[UserRow] = None
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    created_at: Annotated[datetime, Field(title="Created At")]
    attributes: Annotated[dict[str, Any], Field(title="Attributes")]
    version_count: Annotated[int, Field(title="Version Count")]


class PolicySummary(CLIModel):
    policy: PolicyVersionSummary
    """
    Identity of the policy version
    """
    pools: Annotated[list[PoolMembership], Field(title="Pools")]
    """
    Pool membership details for this policy
    """
    entered_at: Annotated[str, Field(title="Entered At")]
    """
    ISO 8601 timestamp of when the policy entered the season
    """


class PolicyVersionRow(CLIModel):
    user_id: Annotated[str, Field(title="User Id")]
    user: Optional[UserRow] = None
    id: Annotated[UUID, Field(title="Id")]
    policy_id: Annotated[UUID, Field(title="Policy Id")]
    name: Annotated[str, Field(title="Name")]
    version: Annotated[int, Field(title="Version")]
    created_at: Annotated[datetime, Field(title="Created At")]
    policy_created_at: Annotated[datetime, Field(title="Policy Created At")]
    tags: Annotated[Optional[dict[str, str]], Field(title="Tags")] = None
    attributes: Annotated[Optional[dict[str, Any]], Field(title="Attributes")] = None
    internal_id: Annotated[Optional[int], Field(title="Internal Id")] = None
    s3_path: Annotated[Optional[str], Field(title="S3 Path")] = None


class PolicyVersionsResponse(CLIModel):
    entries: Annotated[list[PolicyVersionRow], Field(title="Entries")]
    total_count: Annotated[int, Field(title="Total Count")]


class EpisodeResponse(CLIModel):
    id: Annotated[UUID, Field(title="Id")]
    """
    Unique episode identifier
    """
    replay_url: Annotated[Optional[str], Field(title="Replay Url")] = None
    """
    URL to the episode replay recording
    """
    thumbnail_url: Annotated[Optional[str], Field(title="Thumbnail Url")] = None
    """
    URL to a thumbnail image of the episode
    """
    tags: Annotated[dict[str, str], Field(title="Tags")]
    """
    Key-value tags attached to this episode. Common keys: game (game name, e.g. 'cogsguard'), match_type (e.g. 'self_play', 'pairing'), job_id, scheduler_git_ref.
    """
    game_stats: Annotated[
        dict[str, float],
        Field(
            examples=[
                {
                    "objects.agent.agent": 10.0,
                    "objects.aligner_station": 1.0,
                    "objects.carbon_extractor": 48.0,
                    "objects.chest": 2.0,
                    "objects.hub": 1.0,
                    "objects.junction": 107.0,
                    "objects.wall": 3304.0,
                    "tokens_dropped": 0.0,
                    "tokens_free_space": 1622361.0,
                    "tokens_written": 379639.0,
                }
            ],
            title="Game Stats",
        ),
    ]
    """
    Game-level aggregate statistics. Keys include object counts (objects.<type>, e.g. objects.junction, objects.wall, objects.agent.agent, objects.hub, objects.chest, objects.*_extractor, objects.*_station) and observation token stats (tokens_written, tokens_dropped, tokens_free_space).
    """
    policy_results: Annotated[list[PolicyResult], Field(title="Policy Results")]
    """
    Results broken down by policy
    """
    steps: Annotated[Optional[int], Field(title="Steps")] = None
    """
    Number of environment steps in the episode
    """
    created_at: Annotated[datetime, Field(title="Created At")]
    """
    When the episode was recorded
    """


class MatchResponse(CLIModel):
    id: Annotated[UUID, Field(title="Id")]
    """
    Unique match identifier
    """
    season_name: Annotated[str, Field(title="Season Name")]
    """
    Name of the season this match belongs to
    """
    pool_name: Annotated[str, Field(title="Pool Name")]
    """
    Name of the pool this match was played in
    """
    status: Annotated[str, Field(title="Status")]
    """
    Match status: pending, running, completed, or failed
    """
    assignments: Annotated[list[int], Field(title="Assignments")]
    """
    Per-agent policy index assignment
    """
    players: Annotated[list[MatchPlayerInfo], Field(title="Players")]
    """
    Participating policies and their results
    """
    error: Annotated[Optional[str], Field(title="Error")] = None
    """
    Error message if the match failed
    """
    episode_id: Annotated[Optional[UUID], Field(title="Episode Id")] = None
    """
    Episode identifier, present if a game was recorded
    """
    job_id: Annotated[Optional[UUID], Field(title="Job Id")] = None
    """
    Job identifier, present if match has an associated job
    """
    episode: Optional[EpisodeResponse] = None
    """
    Full episode data, included in detail responses
    """
    created_at: Annotated[datetime, Field(title="Created At")]
    """
    When the match was created
    """


class PoliciesResponse(CLIModel):
    entries: Annotated[list[PolicyRow], Field(title="Entries")]
    total_count: Annotated[int, Field(title="Total Count")]
