pools:
  - name: jobs-warm
    workload: jobs
    replicas: 50
    expireAfter: 2h
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        # will prefer spot but fall back to on-demand if spot is not available
        # expireAfter is important for cycling back to spot
        values: ["spot", "on-demand"]

      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["r5a.2xlarge", "r5.2xlarge", "r6a.2xlarge", "r6i.2xlarge", "r7a.2xlarge", "r7i.2xlarge"]

  - name: jobs
    workload: jobs
    requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]

      - key: eks.amazonaws.com/instance-cpu
        operator: In
        values: ["8", "12", "16"]

      - key: eks.amazonaws.com/instance-memory
        operator: Gt
        values: ["16384"]
