image:
  registry: 751442549699.dkr.ecr.us-east-1.amazonaws.com
  name: softmax-com
  tag: "" # will be set by CI/CD pipeline

host: softmax.com
internal_host: softmax-com.softmax-research.net

cert_manager_issuer: letsencrypt

frontend:
  secret_name: softmax-com-frontend-secrets
  replicas: 2
  min_available: 1

observatory_api_url: http://observatory-backend.observatory.svc.cluster.local:8000

policy_dashboard_url: https://vibeservatory.softmax-research.net/policy-dashboard
diagnose_url: https://vibeservatory.softmax-research.net/diagnose
pantheon_url: https://vibeservatory.softmax-research.net
train_board_url: https://api.vibeservatory.softmax-research.net/train-board
chatprop_url: https://api.vibeservatory.softmax-research.net/chatprop
bardo_url: https://vibeservatory.softmax-research.net/bardo

db_migrate: true
cronjobs: true
