image:
  registry: 751442549699.dkr.ecr.us-east-1.amazonaws.com
  name: softmax-com
  tag: "" # will be set by CI/CD pipeline

host: softmax.com
internal_host: softmax-com.softmax-research.net

cert_manager_issuer: letsencrypt

frontend:
  secret_name: softmax-com-frontend-secrets
  replicas: 2
  min_available: 1

observatory_api_url: https://api.observatory.softmax-research.net

policy_dashboard_url: https://policy-dashboard.softmax-research.net

db_migrate: true
cronjobs: true
