apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-chatprop
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.frontendHost | required "frontendHost is required" | quote }}
    http:
      paths:
      - path: {{ .Values.chatprop.path | required "chatprop.path is required" | quote }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 8010
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-trainboard
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.frontendHost | required "frontendHost is required" | quote }}
    http:
      paths:
      - path: {{ .Values.trainboard.path | required "trainboard.path is required" | quote }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 8010
