{{- if .Values.chatprop.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chatprop
spec:
  selector:
    app: {{ .Release.Name }}-chatprop
  ports:
  - port: {{ .Values.chatprop.port }}
    targetPort: {{ .Values.chatprop.port }}
    protocol: TCP
    name: http
---
{{- end }}
{{- if .Values.trainboard.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-trainboard
spec:
  selector:
    app: {{ .Release.Name }}-trainboard
  ports:
  - port: {{ .Values.trainboard.port }}
    targetPort: {{ .Values.trainboard.port }}
    protocol: TCP
    name: http
{{- end }}
