"""Type stubs for tensordict package."""

from typing import Any, KeysView, overload

import torch
from torch import Tensor


class TensorDictBase:
    def __getattr__(self, name: str) -> Any: ...


class TensorDict(TensorDictBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    @overload
    def __getitem__(self, key: str) -> Any: ...
    @overload
    def __getitem__(self, key: int | slice | Tensor | tuple[Any, ...]) -> "TensorDict": ...

    def __setitem__(self, key: str, value: Any) -> None: ...
    def __contains__(self, key: str) -> bool: ...

    def keys(
        self,
        include_nested: bool = False,
        leaves_only: bool = False,
        is_leaf: Any = None,
    ) -> KeysView[str]: ...

    def get(self, key: str | tuple[str, ...], default: Any = None) -> Any: ...
    def set(self, key: str, value: Tensor, **kwargs: Any) -> "TensorDict": ...
    def select(self, *keys: str | tuple[str, ...], strict: bool = True) -> "TensorDict": ...
    def update(self, other: dict[str, Any] | "TensorDict", **kwargs: Any) -> "TensorDict": ...
    def update_at_(self, other: "TensorDict", idx: tuple[Any, ...] | Tensor | int) -> "TensorDict": ...
    def reshape(self, *shape: int) -> "TensorDict": ...
    def clone(self, recurse: bool = True) -> "TensorDict": ...


class NonTensorData:
    def __init__(self, data: Any, *, batch_size: torch.Size | tuple[int, ...] | None = None) -> None: ...

    @property
    def data(self) -> Any: ...


tensordict = TensorDict
