{{ if .Values.db_migrate }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-migrate"
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-db-migrate"
    spec:
      restartPolicy: Never
      containers:
        - name: nextjs
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ required "image.tag" .Values.image.tag }}"
          imagePullPolicy: Always
          command: ["pnpm", "db:migrate:deploy"]
          envFrom:
          - secretRef:
              name: {{ .Values.frontend.secret_name }}
          resources:
            requests:
              memory: "128Mi"
              ephemeral-storage: "2Gi"
            limits:
              memory: "1Gi"
{{ end }}
