apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: nextjs
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ required "image.tag" .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: AUTH_TRUST_HOST
              value: "true"
            - name: OBSERVATORY_POLICY_DASHBOARD_URL
              value: "{{ .Values.policy_dashboard_url }}"
            - name: OBSERVATORY_DIAGNOSE_URL
              value: "{{ .Values.diagnose_url }}"
            - name: OBSERVATORY_PANTHEON_URL
              value: "{{ .Values.pantheon_url }}"
            - name: OBSERVATORY_TRAIN_BOARD_URL
              value: "{{ .Values.train_board_url }}"
            - name: OBSERVATORY_CHATPROP_URL
              value: "{{ .Values.chatprop_url }}"
            - name: OBSERVATORY_BARDO_URL
              value: "{{ .Values.bardo_url }}"
            - name: NEXTAUTH_URL
              value: https://{{ required "host" .Values.host }}
            - name: OBSERVATORY_API_URL
              value: {{ required "observatory_api_url" .Values.observatory_api_url }}
            {{- if .Values.otel.enabled }}
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(HOST_IP):4318"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment={{ required "otel.env is required" .Values.otel.env }},service.version={{ .Values.image.tag }}"
            {{- end }}
          envFrom:
          - secretRef:
              name: {{ .Values.frontend.secret_name }}
          resources:
            requests:
              memory: "1Gi"
              ephemeral-storage: "2Gi"
            limits:
              memory: "4Gi"
