version: "0.5"

processes:
  postgres:
    command: metta softmax-com postgres up
    readiness_probe:
      exec:
        command: python -c "import socket; socket.create_connection(('${POSTGRES_HOST}', ${POSTGRES_PORT}), timeout=1)"
      initial_delay_seconds: 1
      period_seconds: 2

  frontend:
    command: metta softmax-com frontend
