name: "Build Home Frontend Docker Image"

on:
  push:
    branches:
      - main
    paths:
      - "home/**"
      - ".github/workflows/build-home-image.yml"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/_build-and-deploy.yml
    secrets: inherit
    with:
      image_name: softmax-home
      dockerfile: home/Dockerfile
      namespace: default
      release: home
      chart: ./devops/charts/home
      pre_deploy_command: |
        cp home/links.yaml devops/charts/home/
