name: "Build Observatory Backend Docker Image"

on:
  push:
    branches:
      - main
    paths:
      - "app_backend/**"
      - ".github/workflows/build-app-backend-image.yml"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/_build-and-deploy.yml
    with:
      image_name: metta-app-backend
      dockerfile: ./app_backend/Dockerfile
      namespace: observatory
      release: observatory-backend
      chart: ./devops/charts/observatory-backend
