name: "Build Policy Evaluator Docker Image"

on:
  push:
    branches:
      - main
    paths:
      - "app_backend/**"
      - "metta/sim/**"
      - ".github/workflows/build-policy-evaluator-image.yml"
  workflow_dispatch: {}

jobs:
  build-and-push-image:
    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/_build-and-deploy.yml
    secrets: inherit
    with:
      image_name: metta-policy-evaluator
      dockerfile: ./devops/docker/Dockerfile.policy_evaluator
      namespace: orchestrator
      release: orchestrator
      chart: ./devops/charts/orchestrator
